### ISSUE TITLE
Funcionalidad necesaria

### ISSUE THREAD

**Issue by ManuelaFlores** [Manu160296/cardify#5]
# Descripción : 
Implementar funcionalidad necesaria :

**Comment by Rocciescobar** [comment]
- Elaborar función Cardify que realice lo siguiente:

- [x] Agregar etiqueta `<figure>` a cada elemento `<img>` que se encuentre dentro del contenedor.

- [x] Agregar etiqueta `<figcaption>` a cada elemento `<img>` que se encuentre dentro del contenedor.

- [x] Mostrar información del atributo 'alt' al hacer hover sobre cada imagen, incluye estilos.

- Elaborar función Responsive.

**Comment by Rocciescobar** [comment]
- [x] Separar los estilos css del archivo index.js y colocarlos en un nuevo archivo llamado index.css
